import React, { useState, useEffect, useRef } from 'react';
import { 
  Mic, 
  StopCircle, 
  FileText, 
  Download, 
  ChevronLeft, 
  Play, 
  Pause,
  Clock, 
  User, 
  Settings, 
  LogOut,
  Sparkles,
  CheckCircle,
  Wifi,
  WifiOff,
  Globe,
  Edit3,
  Check,
  X,
  Search,
  Moon,
  Sun,
  BrainCircuit,
  HelpCircle,
  SkipBack,
  SkipForward,
  Star,
  Highlighter,
  Share2,
  ZoomIn,
  ZoomOut,
  Network,
  Filter
} from 'lucide-react';

/**
 * TRANSLATIONS
 * 多语言配置
 */
const TRANSLATIONS = {
  'zh-CN': {
    app_name: 'Lecture Note AI',
    slogan: '听得懂，记得住',
    access_code: '访问码 / 账号',
    password: '密码',
    enter_class: '进入课堂',
    verifying: '验证中...',
    my_lectures: '我的讲座',
    welcome: '欢迎回来，同学',
    start_new: '开始新讲座',
    processing: 'AI 处理中',
    waiting_audio: '等待讲师说话...',
    listening: '正在聆听...',
    stop_generate: '结束并生成总结',
    upload_notice: '音频将上传至服务器处理，点击结束触发 AI 总结',
    transcript: '逐字稿',
    ai_summary: 'AI 总结',
    mind_map: '思维导图',
    highlights_tab: '重点回顾',
    export: '导出',
    export_title: '下载讲座资料',
    raw_script: '英文原稿 (Raw)',
    bilingual_doc: '中英对照全文',
    summary_doc: 'AI 智能总结',
    edit_title: '修改标题',
    save: '保存',
    cancel: '取消',
    live_sync: '实时同步',
    rec: '录音中',
    new_lecture_default: '新讲座会话',
    lecture_summary_title: '讲座总结：计算机网络基础 (TCP/IP)',
    core_summary: '核心摘要',
    key_concepts: '关键概念',
    qa_focus: 'Q&A 重点',
    ai_analysis: 'AI 智能分析',
    ai_analysis_desc: '本总结由 DeepSeek 模型生成，包含核心摘要、知识点结构图和复习建议。',
    search_placeholder: '搜索讲座标题...',
    no_results: '未找到相关讲座',
    theme_dark: '深色',
    theme_light: '浅色',
    play_audio: '播放录音',
    pause_audio: '暂停录音',
    mind_map_desc: 'AI 自动提取讲座逻辑结构，生成可视化思维导图。',
    download_map: '下载导图',
    preview_map: '全屏预览',
    highlight_tip: '高亮',
    favorite_tip: '收藏',
    marked_important: '已标记为重点',
    added_favorite: '已加入收藏夹',
    no_highlights: '暂无重点标记',
    highlights_intro: '这里汇集了你在课堂上标记的所有重点和收藏句子。',
    filter_all: '全部',
    filter_highlight: '仅高亮',
    filter_star: '仅收藏'
  },
  'zh-TW': {
    app_name: 'Lecture Note AI',
    slogan: '聽得懂，記得住',
    access_code: '訪問碼 / 賬號',
    password: '密碼',
    enter_class: '進入課堂',
    verifying: '驗證中...',
    my_lectures: '我的講座',
    welcome: '歡迎回來，同學',
    start_new: '開始新講座',
    processing: 'AI 處理中',
    waiting_audio: '等待講師說話...',
    listening: '正在聆聽...',
    stop_generate: '結束並生成總結',
    upload_notice: '音頻將上傳至服務器處理，點擊結束觸發 AI 總結',
    transcript: '逐字稿',
    ai_summary: 'AI 總結',
    mind_map: '思維導圖',
    highlights_tab: '重點回顧',
    export: '導出',
    export_title: '下載講座資料',
    raw_script: '英文原稿 (Raw)',
    bilingual_doc: '中英對照全文',
    summary_doc: 'AI 智能總結',
    edit_title: '修改標題',
    save: '保存',
    cancel: '取消',
    live_sync: '實時同步',
    rec: '錄音中',
    new_lecture_default: '新講座會話',
    lecture_summary_title: '講座總結：計算機網絡基礎 (TCP/IP)',
    core_summary: '核心摘要',
    key_concepts: '關鍵概念',
    qa_focus: 'Q&A 重點',
    ai_analysis: 'AI 智能分析',
    ai_analysis_desc: '本總結由 DeepSeek 模型生成，包含核心摘要、知識點結構圖和複習建議。',
    search_placeholder: '搜索講座標題...',
    no_results: '未找到相關講座',
    theme_dark: '深色',
    theme_light: '淺色',
    play_audio: '播放錄音',
    pause_audio: '暫停錄音',
    mind_map_desc: 'AI 自動提取講座邏輯結構，生成可視化思維導圖。',
    download_map: '下載導圖',
    preview_map: '全屏預覽',
    highlight_tip: '高亮',
    favorite_tip: '收藏',
    marked_important: '已標記為重點',
    added_favorite: '已加入收藏夾',
    no_highlights: '暫無重點標記',
    highlights_intro: '這裡彙集了你在課堂上標記的所有重點和收藏句子。',
    filter_all: '全部',
    filter_highlight: '僅高亮',
    filter_star: '僅收藏'
  },
  'en': {
    app_name: 'Lecture Note AI',
    slogan: 'Understand Better, Remember More',
    access_code: 'Access Code / ID',
    password: 'Password',
    enter_class: 'Enter Class',
    verifying: 'Verifying...',
    my_lectures: 'My Lectures',
    welcome: 'Welcome back, Student',
    start_new: 'Start New',
    processing: 'Processing',
    waiting_audio: 'Waiting for speech...',
    listening: 'Listening...',
    stop_generate: 'End & Summarize',
    upload_notice: 'Audio will be uploaded for processing. Click End to trigger AI summary.',
    transcript: 'Transcript',
    ai_summary: 'AI Summary',
    mind_map: 'Mind Map',
    highlights_tab: 'Highlights',
    export: 'Export',
    export_title: 'Download Materials',
    raw_script: 'Raw Transcript (EN)',
    bilingual_doc: 'Bilingual Doc (EN/ZH)',
    summary_doc: 'AI Smart Summary',
    edit_title: 'Edit Title',
    save: 'Save',
    cancel: 'Cancel',
    live_sync: 'Live Sync',
    rec: 'REC',
    new_lecture_default: 'New Lecture Session',
    lecture_summary_title: 'Lecture Summary: Computer Networks (TCP/IP)',
    core_summary: 'Executive Summary',
    key_concepts: 'Key Concepts',
    qa_focus: 'Q&A Highlights',
    ai_analysis: 'AI Analysis',
    ai_analysis_desc: 'Generated by DeepSeek model, including core summary, key concepts, and review suggestions.',
    search_placeholder: 'Search lectures...',
    no_results: 'No lectures found',
    theme_dark: 'Dark',
    theme_light: 'Light',
    play_audio: 'Play Audio',
    pause_audio: 'Pause Audio',
    mind_map_desc: 'AI automatically extracts logical structure to generate visual mind maps.',
    download_map: 'Download Map',
    preview_map: 'Fullscreen',
    highlight_tip: 'Highlight',
    favorite_tip: 'Favorite',
    marked_important: 'Marked as Important',
    added_favorite: 'Added to Favorites',
    no_highlights: 'No highlights yet',
    highlights_intro: 'Collection of all your highlighted and bookmarked sentences.',
    filter_all: 'All',
    filter_highlight: 'Highlights',
    filter_star: 'Favorites'
  }
};

/**
 * MOCK DATA - MIND MAP
 */
const MIND_MAP_DATA = {
  id: 'root',
  label: 'TCP/IP Protocol',
  children: [
    {
      id: 'l1',
      label: 'Application Layer',
      children: [
        { id: 'l1-1', label: 'HTTP / HTTPS' },
        { id: 'l1-2', label: 'DNS' }
      ]
    },
    {
      id: 'l2',
      label: 'Transport Layer',
      children: [
        { id: 'l2-1', label: 'TCP (Reliable)' },
        { id: 'l2-2', label: 'UDP (Fast)' },
        { id: 'l2-3', label: '3-Way Handshake' }
      ]
    },
    {
      id: 'l3',
      label: 'Internet Layer',
      children: [
        { id: 'l3-1', label: 'IP Addressing' },
        { id: 'l3-2', label: 'Routing' }
      ]
    }
  ]
};

/**
 * MOCK DATA - STREAM
 * Added isHighlighted and isBookmarked fields
 */
const INITIAL_STREAM_DATA = [
  { text_en: "Good morning everyone, let's start today's lecture.", text_zh: "大家早上好，我们开始今天的讲座。", isHighlighted: false, isBookmarked: false },
  { text_en: "Today we are going to talk about the TCP/IP protocol suite.", text_zh: "今天我们将讨论 TCP/IP 协议套件。", isHighlighted: true, isBookmarked: false },
  { text_en: "It is the conceptual model and set of communications protocols used in the Internet.", text_zh: "它是互联网中使用的概念模型和通信协议集。", isHighlighted: false, isBookmarked: false },
  { text_en: "Can anyone tell me what the four layers are?", text_zh: "有谁能告诉我这四层是什么吗？", isHighlighted: false, isBookmarked: false },
  { text_en: "Ideally, we have the Application, Transport, Internet, and Link layers.", text_zh: "理想情况下，我们有应用层、传输层、网络层和链路层。", isHighlighted: false, isBookmarked: true },
  { text_en: "Let's focus on the Transport layer first.", text_zh: "让我们先关注传输层。", isHighlighted: false, isBookmarked: false },
  { text_en: "Specifically, the reliable data transfer provided by TCP.", text_zh: "具体来说，是 TCP 提供的可靠数据传输。", isHighlighted: true, isBookmarked: true },
];

/**
 * COMPONENT: AUDIO VISUALIZER
 */
const AudioVisualizer = ({ isRecording }) => {
  return (
    <div className="flex items-center justify-center space-x-1 h-8">
      {[...Array(5)].map((_, i) => (
        <div
          key={i}
          className={`w-1 bg-red-500 rounded-full transition-all duration-150 ${
            isRecording ? 'animate-pulse' : 'h-1'
          }`}
          style={{
            height: isRecording ? `${Math.random() * 24 + 4}px` : '4px',
            animationDelay: `${i * 0.1}s`
          }}
        />
      ))}
    </div>
  );
};

/**
 * COMPONENT: LANGUAGE & THEME SWITCHER
 */
const TopControls = ({ currentLang, setLang, darkMode, setDarkMode, className = "" }) => {
  const toggleLang = () => {
    if (currentLang === 'zh-CN') setLang('zh-TW');
    else if (currentLang === 'zh-TW') setLang('en');
    else setLang('zh-CN');
  };

  const getLabel = (lang) => {
    switch(lang) {
      case 'zh-CN': return '简';
      case 'zh-TW': return '繁';
      case 'en': return 'EN';
      default: return '简';
    }
  };

  return (
    <div className={`flex items-center space-x-2 ${className}`}>
      <button 
        onClick={() => setDarkMode(!darkMode)}
        className="p-1.5 rounded-full bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-600 transition"
      >
        {darkMode ? <Sun size={14} /> : <Moon size={14} />}
      </button>
      <button 
        onClick={toggleLang}
        className="flex items-center space-x-1 px-3 py-1.5 rounded-full bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 text-xs font-medium hover:bg-slate-200 dark:hover:bg-slate-600 transition"
      >
        <Globe size={14} />
        <span>{getLabel(currentLang)}</span>
      </button>
    </div>
  );
};

/**
 * COMPONENT: MIND MAP NODE (Recursive)
 */
const MindMapNode = ({ node, level = 0 }) => {
  return (
    <div className="flex flex-col items-center">
      <div 
        className={`
          relative px-4 py-2 rounded-lg border-2 shadow-sm transition hover:scale-105 cursor-pointer mb-4
          ${level === 0 ? 'bg-blue-600 text-white border-blue-600 text-lg font-bold' : ''}
          ${level === 1 ? 'bg-white dark:bg-slate-800 text-slate-800 dark:text-white border-blue-400 font-semibold' : ''}
          ${level === 2 ? 'bg-slate-50 dark:bg-slate-700 text-slate-600 dark:text-slate-200 border-slate-300 dark:border-slate-500 text-sm' : ''}
        `}
      >
        {node.label}
      </div>
      
      {node.children && node.children.length > 0 && (
        <div className="flex space-x-4 md:space-x-8 items-start relative before:absolute before:top-0 before:left-1/2 before:-translate-x-1/2 before:h-4 before:w-0.5 before:bg-slate-300 dark:before:bg-slate-600 before:-mt-4">
          {node.children.map((child) => (
            <div key={child.id} className="flex flex-col items-center relative pt-4 before:absolute before:top-0 before:left-1/2 before:-translate-x-1/2 before:h-4 before:w-0.5 before:bg-slate-300 dark:before:bg-slate-600">
              <div className="absolute top-0 w-full border-t-2 border-slate-300 dark:border-slate-600"></div> 
              <MindMapNode node={child} level={level + 1} />
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

/**
 * COMPONENT: LOGIN
 */
const LoginView = ({ onLogin, t, lang, setLang, darkMode, setDarkMode }) => {
  const [loading, setLoading] = useState(false);

  const handleLogin = (e) => {
    e.preventDefault();
    setLoading(true);
    setTimeout(() => {
      onLogin("mock_token_12345");
      setLoading(false);
    }, 800);
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-slate-50 dark:bg-slate-900 p-4 relative transition-colors duration-300">
      <div className="absolute top-4 right-4">
        <TopControls currentLang={lang} setLang={setLang} darkMode={darkMode} setDarkMode={setDarkMode} />
      </div>

      <div className="bg-white dark:bg-slate-800 p-8 rounded-2xl shadow-xl w-full max-w-sm transition-colors duration-300">
        <div className="flex justify-center mb-6">
          <div className="bg-blue-600 p-3 rounded-xl shadow-lg shadow-blue-500/30">
            <Mic className="text-white w-8 h-8" />
          </div>
        </div>
        <h1 className="text-2xl font-bold text-center text-slate-800 dark:text-white mb-2">{t('app_name')}</h1>
        <p className="text-center text-slate-500 dark:text-slate-400 mb-8">{t('slogan')}</p>
        
        <form onSubmit={handleLogin} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">{t('access_code')}</label>
            <input 
              type="text" 
              className="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 dark:bg-slate-700 dark:text-white rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition"
              defaultValue="admin"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">{t('password')}</label>
            <input 
              type="password" 
              className="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 dark:bg-slate-700 dark:text-white rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition"
              defaultValue="password"
            />
          </div>
          <button 
            disabled={loading}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-lg transition duration-200 flex justify-center items-center shadow-md"
          >
            {loading ? t('verifying') : t('enter_class')}
          </button>
        </form>
      </div>
    </div>
  );
};

/**
 * COMPONENT: DASHBOARD
 */
const DashboardView = ({ lectures, onStartLecture, onViewLecture, onLogout, t, lang, setLang, darkMode, setDarkMode }) => {
  const [searchTerm, setSearchTerm] = useState("");

  const filteredLectures = lectures.filter(l => 
    l.title.toLowerCase().includes(searchTerm.toLowerCase()) || 
    l.date.includes(searchTerm)
  );

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 pb-24 transition-colors duration-300">
      {/* Header */}
      <header className="bg-white dark:bg-slate-800 px-6 py-4 shadow-sm flex justify-between items-center sticky top-0 z-10 transition-colors duration-300">
        <div>
          <h1 className="text-xl font-bold text-slate-800 dark:text-white">{t('my_lectures')}</h1>
          <p className="text-xs text-slate-500 dark:text-slate-400">{t('welcome')}</p>
        </div>
        <div className="flex items-center space-x-3">
          <TopControls currentLang={lang} setLang={setLang} darkMode={darkMode} setDarkMode={setDarkMode} />
          <button onClick={onLogout} className="p-2 text-slate-400 hover:text-red-500 transition rounded-full hover:bg-red-50 dark:hover:bg-red-900/20">
            <LogOut size={20} />
          </button>
        </div>
      </header>

      {/* Search Bar */}
      <div className="px-4 mt-6 max-w-2xl mx-auto">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
          <input 
            type="text" 
            placeholder={t('search_placeholder')}
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-3 bg-white dark:bg-slate-800 border-none rounded-xl shadow-sm focus:ring-2 focus:ring-blue-500 text-slate-700 dark:text-slate-200 outline-none transition"
          />
        </div>
      </div>

      {/* List */}
      <div className="p-4 space-y-4 max-w-2xl mx-auto mt-2">
        {filteredLectures.length === 0 ? (
          <div className="text-center text-slate-400 py-10">
            <Search size={48} className="mx-auto mb-2 opacity-20" />
            <p>{t('no_results')}</p>
          </div>
        ) : (
          filteredLectures.map(lecture => (
            <div 
              key={lecture.id} 
              onClick={() => onViewLecture(lecture)}
              className="bg-white dark:bg-slate-800 p-4 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 active:scale-95 transition-all cursor-pointer hover:shadow-md dark:hover:shadow-slate-700/50"
            >
              <div className="flex justify-between items-start mb-2">
                <h3 className="font-semibold text-slate-800 dark:text-white line-clamp-2">{lecture.title}</h3>
                {lecture.status === 'completed' ? (
                  <CheckCircle size={16} className="text-green-500 shrink-0 ml-2" />
                ) : (
                  <span className="shrink-0 ml-2 text-xs bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-400 px-2 py-0.5 rounded-full whitespace-nowrap">{t('processing')}</span>
                )}
              </div>
              <div className="flex items-center text-sm text-slate-500 dark:text-slate-400 space-x-4">
                <span className="flex items-center"><Clock size={14} className="mr-1"/> {lecture.date}</span>
                <span className="flex items-center"><Play size={14} className="mr-1"/> {lecture.duration}</span>
              </div>
            </div>
          ))
        )}
      </div>

      {/* FAB */}
      <div className="fixed bottom-6 right-6 md:right-1/2 md:translate-x-[320px]">
        <button 
          onClick={onStartLecture}
          className="bg-blue-600 text-white p-4 rounded-full shadow-lg hover:bg-blue-700 hover:scale-105 transition flex items-center shadow-blue-500/30"
        >
          <Mic size={24} />
          <span className="ml-2 font-semibold pr-2">{t('start_new')}</span>
        </button>
      </div>
    </div>
  );
};

/**
 * COMPONENT: LIVE SESSION
 */
const LiveSessionView = ({ onEndSession, t }) => {
  const [subtitles, setSubtitles] = useState([]);
  const [isRecording, setIsRecording] = useState(true);
  const [connectionStatus, setConnectionStatus] = useState("connected");
  const scrollRef = useRef(null);

  useEffect(() => {
    let interval;
    if (isRecording) {
      let index = 0;
      interval = setInterval(() => {
        if (index < INITIAL_STREAM_DATA.length) {
          const newData = { 
            ...INITIAL_STREAM_DATA[index], 
            timestamp: new Date().toLocaleTimeString(), 
            id: Date.now() 
          };
          setSubtitles(prev => [...prev, newData]);
          index++;
        }
      }, 3000);
    }
    return () => clearInterval(interval);
  }, [isRecording]);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [subtitles]);

  // Toggle Highlight
  const toggleHighlight = (id) => {
    setSubtitles(prev => prev.map(sub => 
      sub.id === id ? { ...sub, isHighlighted: !sub.isHighlighted } : sub
    ));
  };

  // Toggle Bookmark
  const toggleBookmark = (id) => {
    setSubtitles(prev => prev.map(sub => 
      sub.id === id ? { ...sub, isBookmarked: !sub.isBookmarked } : sub
    ));
  };

  return (
    <div className="flex flex-col h-screen bg-slate-50 dark:bg-slate-900 transition-colors duration-300">
      {/* Top Bar */}
      <div className="bg-white dark:bg-slate-800 px-4 py-3 shadow-sm flex justify-between items-center z-10 transition-colors duration-300">
        <div className="flex items-center space-x-3">
          <AudioVisualizer isRecording={isRecording} />
          <span className={`${isRecording ? 'text-red-500' : 'text-slate-400'} font-medium text-sm font-mono`}>
             00:04:12
          </span>
        </div>
        <div className="flex items-center space-x-2">
          {connectionStatus === 'connected' ? 
            <Wifi size={16} className="text-green-500"/> : 
            <WifiOff size={16} className="text-gray-400"/>
          }
          <span className="text-xs text-slate-400">{t('live_sync')}</span>
        </div>
      </div>

      {/* Subtitle Stream Area */}
      <div 
        ref={scrollRef}
        className="flex-1 overflow-y-auto p-4 space-y-4 scroll-smooth"
      >
        {subtitles.length === 0 && (
          <div className="flex flex-col items-center justify-center h-full text-slate-400 dark:text-slate-600">
            <Mic size={48} className="mb-4 opacity-20" />
            <p>{t('waiting_audio')}</p>
            <p className="text-xs mt-2">{t('listening')}</p>
          </div>
        )}
        
        {subtitles.map((sub, idx) => (
          <div 
            key={sub.id} 
            className={`
              relative group p-3 rounded-lg border border-transparent transition-all duration-300 animate-in fade-in slide-in-from-bottom-4
              ${sub.isHighlighted 
                ? 'bg-yellow-50 dark:bg-yellow-900/20 border-yellow-200 dark:border-yellow-700/50' 
                : 'hover:bg-white dark:hover:bg-slate-800/50 hover:shadow-sm'
              }
            `}
          >
            <div className="flex justify-between items-start">
              <div className="flex-1 pr-8">
                <p className={`text-lg font-medium leading-relaxed mb-1 transition-colors ${sub.isHighlighted ? 'text-slate-900 dark:text-yellow-50' : 'text-slate-800 dark:text-slate-200'}`}>
                  {sub.text_en}
                </p>
                <p className={`text-base leading-relaxed transition-colors ${sub.isHighlighted ? 'text-slate-700 dark:text-yellow-100/70' : 'text-slate-500 dark:text-slate-400'}`}>
                  {sub.text_zh}
                </p>
              </div>
              
              <div className="flex flex-col items-end space-y-1">
                <span className="text-[10px] text-slate-300 dark:text-slate-600 font-mono">{sub.timestamp}</span>
                {sub.isBookmarked && <Star size={14} className="text-orange-400 fill-orange-400" />}
              </div>
            </div>

            {/* Floating Action Buttons */}
            <div className={`
              absolute top-2 right-2 flex flex-col space-y-2 
              ${(sub.isHighlighted || sub.isBookmarked) ? 'opacity-100' : 'opacity-0 group-hover:opacity-100'} 
              transition-opacity
            `}>
              <button 
                onClick={() => toggleHighlight(sub.id)}
                className={`p-1.5 rounded-full transition ${sub.isHighlighted ? 'bg-yellow-400 text-white' : 'bg-slate-100 dark:bg-slate-700 text-slate-400 hover:text-yellow-500'}`}
              >
                <Highlighter size={14} />
              </button>
              <button 
                onClick={() => toggleBookmark(sub.id)}
                className={`p-1.5 rounded-full transition ${sub.isBookmarked ? 'bg-orange-400 text-white' : 'bg-slate-100 dark:bg-slate-700 text-slate-400 hover:text-orange-500'}`}
              >
                <Star size={14} fill={sub.isBookmarked ? "currentColor" : "none"} />
              </button>
            </div>
          </div>
        ))}
        
        {isRecording && (
          <div className="h-8 flex items-center space-x-1 pl-1 mt-4">
             <div className="w-1.5 h-1.5 bg-slate-300 dark:bg-slate-600 rounded-full animate-bounce delay-75"></div>
             <div className="w-1.5 h-1.5 bg-slate-300 dark:bg-slate-600 rounded-full animate-bounce delay-150"></div>
             <div className="w-1.5 h-1.5 bg-slate-300 dark:bg-slate-600 rounded-full animate-bounce delay-300"></div>
          </div>
        )}
      </div>

      {/* Bottom Controls */}
      <div className="bg-white dark:bg-slate-800 border-t border-slate-100 dark:border-slate-700 p-6 pb-8 transition-colors duration-300">
        <div className="flex justify-center items-center space-x-6">
          <button 
            onClick={() => setIsRecording(!isRecording)}
            className={`p-4 rounded-full transition ${isRecording ? 'bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300' : 'bg-red-50 dark:bg-red-900/20 text-red-500'}`}
          >
            {isRecording ? <Pause size={24} fill="currentColor" /> : <Mic size={24}/>}
          </button>

          <button 
            onClick={onEndSession}
            className="bg-red-500 hover:bg-red-600 text-white px-8 py-4 rounded-full font-semibold shadow-lg shadow-red-500/30 active:scale-95 transition flex items-center"
          >
            <StopCircle className="mr-2" size={20} />
            {t('stop_generate')}
          </button>
        </div>
        <p className="text-center text-xs text-slate-400 mt-4">{t('upload_notice')}</p>
      </div>
    </div>
  );
};

/**
 * COMPONENT: AUDIO PLAYER MOCK
 */
const AudioPlayer = ({ t }) => {
  const [playing, setPlaying] = useState(false);
  const [progress, setProgress] = useState(30);

  return (
    <div className="fixed bottom-0 left-0 right-0 bg-white dark:bg-slate-800 border-t border-slate-200 dark:border-slate-700 p-4 shadow-lg z-20 md:sticky md:bottom-0 md:rounded-b-xl">
      <div className="flex items-center space-x-4 max-w-4xl mx-auto">
        <button 
          onClick={() => setPlaying(!playing)}
          className="bg-blue-600 text-white p-2 rounded-full hover:bg-blue-700 transition"
        >
          {playing ? <Pause size={20} fill="currentColor" /> : <Play size={20} fill="currentColor" />}
        </button>
        <div className="text-xs font-mono text-slate-500 dark:text-slate-400 w-12 text-right">04:12</div>
        <div className="flex-1 relative h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden cursor-pointer">
          <div 
            className="absolute top-0 left-0 h-full bg-blue-500 rounded-full" 
            style={{ width: `${progress}%` }}
          ></div>
        </div>
        <div className="text-xs font-mono text-slate-500 dark:text-slate-400 w-12">12:30</div>
        <div className="flex space-x-2 text-slate-500 dark:text-slate-400">
           <SkipBack size={18} className="hover:text-blue-500 cursor-pointer" />
           <SkipForward size={18} className="hover:text-blue-500 cursor-pointer" />
        </div>
      </div>
    </div>
  );
};

/**
 * COMPONENT: MIND MAP VIEW
 */
const MindMapView = ({ t }) => {
  return (
    <div className="max-w-4xl mx-auto md:bg-white md:dark:bg-slate-800 md:p-8 md:rounded-xl md:shadow-sm min-h-[500px] flex flex-col">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-bold text-slate-800 dark:text-white flex items-center">
            <Network className="mr-2 text-purple-600" />
            {t('mind_map')}
          </h2>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">{t('mind_map_desc')}</p>
        </div>
        <div className="flex space-x-2">
          <button className="p-2 bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-600">
            <ZoomIn size={18} />
          </button>
           <button className="p-2 bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-600">
            <ZoomOut size={18} />
          </button>
        </div>
      </div>

      <div className="flex-1 bg-slate-50 dark:bg-slate-900/50 rounded-xl border border-slate-200 dark:border-slate-700 p-8 overflow-x-auto flex justify-center items-center">
        <div className="min-w-max">
           <MindMapNode node={MIND_MAP_DATA} />
        </div>
      </div>

      <div className="flex justify-end pt-6">
        <button className="flex items-center text-blue-600 hover:text-blue-700 dark:text-blue-400 font-medium px-4 py-2 hover:bg-blue-50 dark:hover:bg-slate-700/50 rounded-lg transition">
          <Download size={18} className="mr-2" />
          {t('download_map')}
        </button>
      </div>
    </div>
  );
};

/**
 * COMPONENT: LECTURE DETAIL
 */
const LectureDetailView = ({ lecture, onBack, onUpdateTitle, t }) => {
  const [activeTab, setActiveTab] = useState('summary');
  const [isEditingTitle, setIsEditingTitle] = useState(false);
  const [editedTitle, setEditedTitle] = useState(lecture?.title);
  const [filterType, setFilterType] = useState('all'); // 'all', 'highlight', 'star'
  
  const [transcriptData, setTranscriptData] = useState(INITIAL_STREAM_DATA.map((item, idx) => ({...item, id: idx})));

  useEffect(() => {
    setEditedTitle(lecture?.title);
  }, [lecture]);

  const handleSaveTitle = () => {
    onUpdateTitle(lecture.id, editedTitle);
    setIsEditingTitle(false);
  };

  const toggleHighlight = (id) => {
    setTranscriptData(prev => prev.map(item => 
      item.id === id ? { ...item, isHighlighted: !item.isHighlighted } : item
    ));
  };

  const toggleBookmark = (id) => {
    setTranscriptData(prev => prev.map(item => 
      item.id === id ? { ...item, isBookmarked: !item.isBookmarked } : item
    ));
  };

  // Filtering for the highlights tab
  const getFilteredHighlights = () => {
    return transcriptData.filter(item => {
      if (filterType === 'all') return item.isHighlighted || item.isBookmarked;
      if (filterType === 'highlight') return item.isHighlighted;
      if (filterType === 'star') return item.isBookmarked;
      return false;
    });
  };

  return (
    <div className="flex flex-col h-screen bg-slate-50 dark:bg-slate-900 transition-colors duration-300">
      {/* Header */}
      <header className="bg-white dark:bg-slate-800 shadow-sm sticky top-0 z-10 transition-colors duration-300">
        <div className="flex items-center p-4">
          <button onClick={onBack} className="p-2 -ml-2 text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-full transition">
            <ChevronLeft size={24} />
          </button>
          
          <div className="ml-2 flex-1 min-w-0">
            {isEditingTitle ? (
              <div className="flex items-center">
                <input 
                  type="text" 
                  value={editedTitle}
                  onChange={(e) => setEditedTitle(e.target.value)}
                  className="flex-1 border-b-2 border-blue-500 focus:outline-none text-slate-800 dark:text-white font-bold px-1 py-1 mr-2 bg-slate-50 dark:bg-slate-800"
                  autoFocus
                />
                <button onClick={handleSaveTitle} className="p-1.5 bg-blue-100 text-blue-600 rounded-full hover:bg-blue-200 mr-1">
                  <Check size={16} />
                </button>
                <button onClick={() => { setIsEditingTitle(false); setEditedTitle(lecture.title); }} className="p-1.5 bg-slate-100 text-slate-500 rounded-full hover:bg-slate-200">
                  <X size={16} />
                </button>
              </div>
            ) : (
              <div className="flex items-center group">
                <h1 className="font-bold text-slate-800 dark:text-white truncate max-w-[200px] md:max-w-md">
                  {lecture?.title}
                </h1>
                <button 
                  onClick={() => setIsEditingTitle(true)}
                  className="ml-2 p-1 text-slate-300 hover:text-blue-500 hover:bg-blue-50 dark:hover:bg-slate-700 rounded transition opacity-0 group-hover:opacity-100 focus:opacity-100"
                  title={t('edit_title')}
                >
                  <Edit3 size={14} />
                </button>
              </div>
            )}
            <p className="text-xs text-slate-500 dark:text-slate-400">{lecture?.date}</p>
          </div>
        </div>
        
        {/* Tabs */}
        <div className="flex px-4 space-x-6 border-b border-slate-100 dark:border-slate-700 overflow-x-auto">
          <button 
            onClick={() => setActiveTab('transcript')}
            className={`pb-3 text-sm font-medium transition border-b-2 whitespace-nowrap ${activeTab === 'transcript' ? 'border-blue-500 text-blue-600 dark:text-blue-400' : 'border-transparent text-slate-500 dark:text-slate-400'}`}
          >
            {t('transcript')}
          </button>
          <button 
            onClick={() => setActiveTab('summary')}
            className={`pb-3 text-sm font-medium transition border-b-2 flex items-center whitespace-nowrap ${activeTab === 'summary' ? 'border-purple-500 text-purple-600 dark:text-purple-400' : 'border-transparent text-slate-500 dark:text-slate-400'}`}
          >
            <Sparkles size={14} className="mr-1" />
            {t('ai_summary')}
          </button>
           <button 
            onClick={() => setActiveTab('mind_map')}
            className={`pb-3 text-sm font-medium transition border-b-2 flex items-center whitespace-nowrap ${activeTab === 'mind_map' ? 'border-green-500 text-green-600 dark:text-green-400' : 'border-transparent text-slate-500 dark:text-slate-400'}`}
          >
            <Network size={14} className="mr-1" />
            {t('mind_map')}
          </button>
          <button 
            onClick={() => setActiveTab('highlights')}
            className={`pb-3 text-sm font-medium transition border-b-2 flex items-center whitespace-nowrap ${activeTab === 'highlights' ? 'border-yellow-500 text-yellow-600 dark:text-yellow-400' : 'border-transparent text-slate-500 dark:text-slate-400'}`}
          >
            <Star size={14} className="mr-1" />
            {t('highlights_tab')}
          </button>
          <button 
            onClick={() => setActiveTab('export')}
            className={`pb-3 text-sm font-medium transition border-b-2 whitespace-nowrap ${activeTab === 'export' ? 'border-slate-800 text-slate-800 dark:border-slate-200 dark:text-slate-200' : 'border-transparent text-slate-500 dark:text-slate-400'}`}
          >
            {t('export')}
          </button>
        </div>
      </header>

      {/* Content Area */}
      <div className="flex-1 overflow-y-auto p-4 md:p-8 max-w-4xl mx-auto w-full bg-white dark:bg-slate-900 md:bg-transparent md:mt-4 relative scroll-smooth">
        
        {/* TAB: TRANSCRIPT */}
        {activeTab === 'transcript' && (
          <div className="pb-20"> {/* Padding for audio player */}
            <div className="space-y-4 md:bg-white md:dark:bg-slate-800 md:p-8 md:rounded-xl md:shadow-sm">
              {transcriptData.map((line, i) => (
                <div 
                  key={i} 
                  className={`
                    group relative p-3 rounded-lg border border-transparent transition-all duration-200
                    ${line.isHighlighted 
                      ? 'bg-yellow-50 dark:bg-yellow-900/20 border-yellow-200 dark:border-yellow-700/50' 
                      : 'hover:bg-slate-50 dark:hover:bg-slate-700/50 hover:shadow-sm'
                    }
                  `}
                >
                  <div className="flex justify-between items-baseline mb-1">
                    <span className="text-xs font-mono text-slate-400 flex items-center gap-1 group-hover:text-blue-500">
                      <Play size={10} className="opacity-0 group-hover:opacity-100 cursor-pointer" />
                      00:0{i}:2{i}
                    </span>
                    {/* Status Icons */}
                    <div className="flex space-x-2">
                       {line.isBookmarked && <Star size={12} className="text-orange-400 fill-orange-400" />}
                    </div>
                  </div>
                  <p className={`text-base mb-1 transition-colors ${line.isHighlighted ? 'text-slate-900 dark:text-yellow-50 font-medium' : 'text-slate-800 dark:text-slate-200'}`}>
                    {line.text_en}
                  </p>
                  <p className={`text-sm transition-colors ${line.isHighlighted ? 'text-slate-700 dark:text-yellow-100/70' : 'text-slate-500 dark:text-slate-400'}`}>
                    {line.text_zh}
                  </p>

                  {/* Actions (Hover) */}
                  <div className="absolute top-2 right-2 flex space-x-1 opacity-0 group-hover:opacity-100 transition-opacity">
                     <button 
                      onClick={() => toggleHighlight(line.id)}
                      className={`p-1.5 rounded bg-white dark:bg-slate-600 shadow-sm border border-slate-200 dark:border-slate-500 ${line.isHighlighted ? 'text-yellow-600 dark:text-yellow-400' : 'text-slate-400 hover:text-yellow-500'}`}
                      title={t('highlight_tip')}
                    >
                      <Highlighter size={14} />
                    </button>
                    <button 
                      onClick={() => toggleBookmark(line.id)}
                       className={`p-1.5 rounded bg-white dark:bg-slate-600 shadow-sm border border-slate-200 dark:border-slate-500 ${line.isBookmarked ? 'text-orange-500 fill-orange-500' : 'text-slate-400 hover:text-orange-500'}`}
                      title={t('favorite_tip')}
                    >
                      <Star size={14} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
            <AudioPlayer t={t} />
          </div>
        )}

        {/* TAB: HIGHLIGHTS (NEW) */}
        {activeTab === 'highlights' && (
           <div className="space-y-4 md:bg-white md:dark:bg-slate-800 md:p-8 md:rounded-xl md:shadow-sm min-h-[500px]">
             {/* Intro & Filters */}
             <div className="flex flex-col md:flex-row md:items-center justify-between mb-6 gap-4">
                <div>
                  <h2 className="text-lg font-bold text-slate-800 dark:text-white mb-1">{t('highlights_tab')}</h2>
                  <p className="text-sm text-slate-500 dark:text-slate-400">{t('highlights_intro')}</p>
                </div>
                
                <div className="flex bg-slate-100 dark:bg-slate-700/50 p-1 rounded-lg">
                   <button 
                    onClick={() => setFilterType('all')}
                    className={`px-3 py-1.5 rounded text-xs font-medium transition ${filterType === 'all' ? 'bg-white dark:bg-slate-600 text-slate-800 dark:text-white shadow-sm' : 'text-slate-500 dark:text-slate-400 hover:text-slate-700'}`}
                   >
                     {t('filter_all')}
                   </button>
                   <button 
                    onClick={() => setFilterType('highlight')}
                    className={`px-3 py-1.5 rounded text-xs font-medium transition flex items-center ${filterType === 'highlight' ? 'bg-white dark:bg-slate-600 text-yellow-600 dark:text-yellow-400 shadow-sm' : 'text-slate-500 dark:text-slate-400 hover:text-slate-700'}`}
                   >
                     <Highlighter size={12} className="mr-1" />
                     {t('filter_highlight')}
                   </button>
                   <button 
                    onClick={() => setFilterType('star')}
                    className={`px-3 py-1.5 rounded text-xs font-medium transition flex items-center ${filterType === 'star' ? 'bg-white dark:bg-slate-600 text-orange-600 dark:text-orange-400 shadow-sm' : 'text-slate-500 dark:text-slate-400 hover:text-slate-700'}`}
                   >
                     <Star size={12} className="mr-1" />
                     {t('filter_star')}
                   </button>
                </div>
             </div>

             {/* List */}
             {getFilteredHighlights().length === 0 ? (
               <div className="flex flex-col items-center justify-center py-20 text-slate-400">
                 <div className="bg-slate-50 dark:bg-slate-800/50 p-4 rounded-full mb-3">
                    <Star size={32} className="opacity-30" />
                 </div>
                 <p>{t('no_highlights')}</p>
               </div>
             ) : (
                <div className="space-y-4">
                  {getFilteredHighlights().map((item) => (
                    <div key={item.id} className="p-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/30 flex gap-4">
                       <div className="mt-1 flex-shrink-0 flex flex-col items-center gap-2">
                          {item.isBookmarked && <Star size={16} className="text-orange-500 fill-orange-500" />}
                          {item.isHighlighted && <Highlighter size={16} className="text-yellow-500" />}
                       </div>
                       <div>
                          <p className="text-sm font-mono text-slate-400 mb-1">00:0{item.id}:2{item.id}</p>
                          <p className={`text-base font-medium mb-1 ${item.isHighlighted ? 'bg-yellow-100 dark:bg-yellow-900/30 px-1 rounded -ml-1 inline-block text-slate-900 dark:text-yellow-100' : 'text-slate-800 dark:text-slate-200'}`}>
                            {item.text_en}
                          </p>
                          <p className="text-slate-500 dark:text-slate-400 text-sm">
                            {item.text_zh}
                          </p>
                       </div>
                    </div>
                  ))}
                </div>
             )}
           </div>
        )}

        {/* TAB: SUMMARY */}
        {activeTab === 'summary' && (
          <div className="prose prose-slate dark:prose-invert prose-headings:font-bold prose-a:text-blue-600 max-w-none md:bg-white md:dark:bg-slate-800 md:p-8 md:rounded-xl md:shadow-sm">
            <div className="bg-purple-50 dark:bg-purple-900/20 border border-purple-100 dark:border-purple-800 p-4 rounded-lg mb-6">
              <div className="flex items-center text-purple-700 dark:text-purple-300 font-semibold mb-2">
                <Sparkles size={18} className="mr-2"/> {t('ai_analysis')}
              </div>
              <p className="text-sm text-purple-600 dark:text-purple-400">{t('ai_analysis_desc')}</p>
            </div>
            
            <h1 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">{t('lecture_summary_title')}</h1>
            
            <h2 className="text-xl font-bold mt-6 mb-3 text-slate-800 dark:text-slate-100">{t('core_summary')}</h2>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
              本次讲座教授深入浅出地讲解了 TCP/IP 协议栈的基础架构。重点阐述了传输层的可靠性机制，特别是三次握手（Three-way Handshake）建立连接的过程，以及四次挥手断开连接的逻辑。
            </p>

            <h2 className="text-xl font-bold mt-6 mb-3 text-slate-800 dark:text-slate-100">{t('key_concepts')}</h2>
            <ul className="list-disc pl-5 space-y-2 text-slate-700 dark:text-slate-300">
              <li><strong className="text-slate-900 dark:text-white">Encapsulation (封装)</strong>: 数据在网络层级中自上而下传递时添加头部信息的过程。</li>
              <li><strong className="text-slate-900 dark:text-white">Handshake (握手)</strong>: 建立连接时的确认机制 (SYN, SYN-ACK, ACK)。</li>
            </ul>

            <h2 className="text-xl font-bold mt-6 mb-3 text-slate-800 dark:text-slate-100">{t('qa_focus')}</h2>
            <div className="border-l-4 border-blue-200 dark:border-blue-700 pl-4 py-1 my-4 bg-slate-50 dark:bg-slate-800/50">
              <p className="font-semibold text-slate-800 dark:text-white">Q: 为什么要三次握手而不是两次？</p>
              <p className="text-slate-600 dark:text-slate-300 mt-1">A: 为了防止已失效的连接请求报文段突然又传送到了服务端，因而产生错误。</p>
            </div>
          </div>
        )}

        {/* TAB: MIND MAP */}
        {activeTab === 'mind_map' && <MindMapView t={t} />}

        {/* TAB: EXPORT */}
        {activeTab === 'export' && (
          <div className="space-y-4 md:bg-white md:dark:bg-slate-800 md:p-8 md:rounded-xl md:shadow-sm">
            <h3 className="font-semibold text-slate-800 dark:text-white mb-4">{t('export_title')}</h3>
            
            <div className="grid gap-4 md:grid-cols-2">
              <button className="flex items-center p-4 border border-slate-200 dark:border-slate-700 rounded-xl hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-slate-700 transition group">
                <div className="bg-blue-100 dark:bg-blue-900/30 p-3 rounded-lg mr-4 group-hover:bg-blue-200 dark:group-hover:bg-blue-800">
                  <FileText className="text-blue-600 dark:text-blue-300" size={24} />
                </div>
                <div className="text-left">
                  <div className="font-medium text-slate-800 dark:text-white">{t('bilingual_doc')}</div>
                  <div className="text-xs text-slate-500 dark:text-slate-400">PDF Document • 2.4 MB</div>
                </div>
                <Download className="ml-auto text-slate-400 group-hover:text-blue-500" size={20} />
              </button>

              <button className="flex items-center p-4 border border-slate-200 dark:border-slate-700 rounded-xl hover:border-purple-500 hover:bg-purple-50 dark:hover:bg-slate-700 transition group">
                <div className="bg-purple-100 dark:bg-purple-900/30 p-3 rounded-lg mr-4 group-hover:bg-purple-200 dark:group-hover:bg-purple-800">
                  <Sparkles className="text-purple-600 dark:text-purple-300" size={24} />
                </div>
                <div className="text-left">
                  <div className="font-medium text-slate-800 dark:text-white">{t('summary_doc')}</div>
                  <div className="text-xs text-slate-500 dark:text-slate-400">Markdown / Word • 0.8 MB</div>
                </div>
                <Download className="ml-auto text-slate-400 group-hover:text-purple-500" size={20} />
              </button>

              <button className="flex items-center p-4 border border-slate-200 dark:border-slate-700 rounded-xl hover:border-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700 transition group">
                <div className="bg-slate-100 dark:bg-slate-700 p-3 rounded-lg mr-4 group-hover:bg-slate-200 dark:group-hover:bg-slate-600">
                  <FileText className="text-slate-600 dark:text-slate-300" size={24} />
                </div>
                <div className="text-left">
                  <div className="font-medium text-slate-800 dark:text-white">{t('raw_script')}</div>
                  <div className="text-xs text-slate-500 dark:text-slate-400">Plain Text • 0.5 MB</div>
                </div>
                <Download className="ml-auto text-slate-400 group-hover:text-slate-500" size={20} />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

/**
 * MAIN APP
 */
export default function App() {
  const [currentView, setCurrentView] = useState('login'); 
  const [authToken, setAuthToken] = useState(null);
  const [activeLecture, setActiveLecture] = useState(null);
  const [lang, setLang] = useState('zh-CN');
  const [darkMode, setDarkMode] = useState(false);

  // Lecture Data State
  const [lectures, setLectures] = useState([
    { id: 101, title: "Operating Systems: Processes", date: "2023-10-24 10:00", duration: "45 min", status: "completed" },
    { id: 102, title: "Linear Algebra: Eigenvalues", date: "2023-10-22 14:00", duration: "90 min", status: "completed" },
    { id: 103, title: "Intro to Psychology", date: "2023-10-20 09:00", duration: "60 min", status: "processing" },
  ]);

  // Apply Dark Mode Class
  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  // Translation Helper
  const t = (key) => TRANSLATIONS[lang][key] || key;

  // Handlers
  const handleLogin = (token) => {
    setAuthToken(token);
    setCurrentView('dashboard');
  };

  const handleStartLecture = () => {
    setCurrentView('live');
  };

  const handleEndSession = () => {
    const newLecture = {
      id: Date.now(),
      title: t('new_lecture_default'),
      date: new Date().toLocaleDateString() + " " + new Date().toLocaleTimeString(),
      duration: "4 min",
      status: "completed"
    };
    setLectures(prev => [newLecture, ...prev]);
    setActiveLecture(newLecture);
    setCurrentView('detail');
  };

  const handleViewLecture = (lecture) => {
    setActiveLecture(lecture);
    setCurrentView('detail');
  };

  const handleBackToDashboard = () => {
    setActiveLecture(null);
    setCurrentView('dashboard');
  };

  // Update Lecture Title
  const handleUpdateLectureTitle = (id, newTitle) => {
    setLectures(prev => prev.map(l => 
      l.id === id ? { ...l, title: newTitle } : l
    ));
    if (activeLecture && activeLecture.id === id) {
      setActiveLecture(prev => ({ ...prev, title: newTitle }));
    }
  };

  // View Router
  switch (currentView) {
    case 'login':
      return <LoginView onLogin={handleLogin} t={t} lang={lang} setLang={setLang} darkMode={darkMode} setDarkMode={setDarkMode} />;
    case 'dashboard':
      return <DashboardView 
        lectures={lectures}
        onStartLecture={handleStartLecture} 
        onViewLecture={handleViewLecture} 
        onLogout={() => setCurrentView('login')}
        t={t} lang={lang} setLang={setLang}
        darkMode={darkMode} setDarkMode={setDarkMode}
      />;
    case 'live':
      return <LiveSessionView onEndSession={handleEndSession} t={t} />;
    case 'detail':
      return <LectureDetailView 
        lecture={activeLecture} 
        onBack={handleBackToDashboard} 
        onUpdateTitle={handleUpdateLectureTitle}
        t={t}
      />;
    default:
      return <LoginView onLogin={handleLogin} t={t} lang={lang} setLang={setLang} darkMode={darkMode} setDarkMode={setDarkMode} />;
  }
}